export default{
    data(){
        return{
            en: {
                selectEn: "English",
                selectSp: "Spanish",
                EncabContact: "Contact Us",
                EncabAboutUs: "About Us",
                EncabHome: "Home",
                slogan: "Transforming a smile is transforming a life",
                especialists: [
                    { nombre: 'Dr. Sandra Milena Bermúdez Giraldo', especialidad: 'General and Aesthetic Dentist', experiencia: '20 years of experience', descripcion: 'My work is focused on...' },
                    { nombre: 'Dr. Jenifer Giraldo Arcila', especialidad: 'Orthodontics', experiencia: '20 years of experience', descripcion: 'I am at the service of the community...' },
                    { nombre: 'Dr. Juan David Jiménez', especialidad: 'Maxillofacial Surgery', experiencia: '20 years of experience', descripcion: 'I am characterized by my dedication to...' },
                    { nombre: 'Dr. Hugo Barrientos', especialidad: 'Implantology and Oral Rehabilitation', experiencia: '20 years of experience', descripcion: 'My work is focused on...' },
                    { nombre: 'Dr. Valentina Henao', especialidad: 'Orofacial Harmonization', experiencia: '20 years of experience', descripcion: 'My work is focused on...' },
                    { nombre: 'Dr. Yeny Berrío', especialidad: 'Periodontics and Oral Implantology', experiencia: '20 years of experience', descripcion: 'My work is focused on...' },
                ],
                titlePost: 'Posts',
                titleServ: 'Our Services',
                seePost: 'See Post',
                BtnCita:'Schedule Your Appointment',
                Address: 'Cra 30 #29-72. Office 207, El Edén Mall. El Carmen de Viboral - Antioquía',
                DataPersonal: 'Personal Data Processing Policy',
                selectData: 'Data Required',
                inteName: 'Full Name',
                inteEmail: 'Email',
                inteProps: 'Purpose',
                inteMessa: 'Message',
                inteCel: 'Cellphone',
                inteImage: 'Profile Picture',
                selecHour: 'Select a Time',
                ModeCiteOnline: 'Online Appointment',
                ModeCitePresent: 'In-person Appointment',
                btnAcept: 'Accept',
                tContact: 'Contact',
                wrHere: 'Write here...',
                wrName: 'Enter your name...',
                wrEmail: 'Enter your email...',
                login: 'Log In',
                sigin: 'Sign In'
            }
        }
    }
}
/*
services:[
                    {name:'General odontology', BenfRes:['',], 
                    Encargados:[{name:'',image:''},],
                    Procedimientos:['',''],
                    ProtoSegEHigiene:['',''],
                    },
                    {name:'Orofacial Harmonization', BenfRes:['',], 
                    Encargados:[{name:'',image:''},],
                    Procedimientos:['',''],
                    ProtoSegEHigiene:['',''],
                    },
                    {name:'Smile Design', BenfRes:['',], 
                    Encargados:[{name:'',image:''},],
                    Procedimientos:['',''],
                    ProtoSegEHigiene:['',''],
                    },
                    {name:'Periodontics', BenfRes:['',], 
                    Encargados:[{name:'',image:''},],
                    Procedimientos:['',''],
                    ProtoSegEHigiene:['',''],
                    },
                    {name:'Implants', BenfRes:['',], 
                    Encargados:[{name:'',image:''},],
                    Procedimientos:['',''],
                    ProtoSegEHigiene:['',''],
                    },
                    {name:'Oral Rehabilitation', BenfRes:['',], 
                    Encargados:[{name:'',image:''},],
                    Procedimientos:['',''],
                    ProtoSegEHigiene:['',''],
                    },
                    {name:'Maxillofacial Surgery', BenfRes:['',], 
                    Encargados:[{name:'',image:''},],
                    Procedimientos:['',''],
                    ProtoSegEHigiene:['',''],
                    },
                    {name:'Endodontics', BenfRes:['',], 
                    Encargados:[{name:'',image:''},],
                    Procedimientos:['',''],
                    ProtoSegEHigiene:['',''],
                    },
                    {name:'Orthodontics', BenfRes:['',], 
                    Encargados:[{name:'',image:''},],
                    Procedimientos:['',''],
                    ProtoSegEHigiene:['',''],
                    },
                    {name:'Conscious Sedation', BenfRes:['',], 
                    Encargados:[{name:'',image:''},],
                    Procedimientos:['',''],
                    ProtoSegEHigiene:['',''],
                    },
                    {name:'Pediatric Dentistry', BenfRes:['',], 
                    Encargados:[{name:'',image:''},],
                    Procedimientos:['',''],
                    ProtoSegEHigiene:['',''],
                    },
                ],
*/